project_id = "tftflkooiwhonyztyode"

[functions.square-create-checkout]
enabled = true
verify_jwt = true
entrypoint = "./functions/square-create-checkout/index.ts"

[functions.square-create-refund]
enabled = true
verify_jwt = true
entrypoint = "./functions/square-create-refund/index.ts"

[functions.square-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/square-webhook/index.ts"

[functions.booking-payment-status]
enabled = true
verify_jwt = true
entrypoint = "./functions/booking-payment-status/index.ts"
